# ====================================================================
# BASIC SITE CONFIGURATION
# ====================================================================
site_name: Sorix
site_description: High-performance, minimalist library for Machine Learning and Deep Learning based on NumPy.
site_url: https://mitchell-mirano.github.io/sorix/
repo_url: https://github.com/Mitchell-Mirano/sorix/
repo_name: Mitchell-Mirano/sorix
edit_uri: edit/{{ branch }}/docs/

# ====================================================================
# 1. MATERIAL THEME CONFIGURATION (FastAPI style)
# ====================================================================
theme:
  name: material
  language: en
  
  palette:
    # --- System preference (Main Toggle) ---
    - media: (prefers-color-scheme)
      toggle:
        icon: material/theme-light-dark
        name: Use system preference
    
    # --- Light Mode ---
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    
    # --- Dark Mode ---
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  
  icon:
    logo: material/book-open-variant
    repo: fontawesome/brands/github
  
  features:
    # Navigation
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.path
    - navigation.top
    - toc.follow
    
    # Content and Code
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    
    # Search
    - search.suggest
    - search.highlight
    - search.share


# ====================================================================
# 2. NAVIGATION STRUCTURE (nav)
# ====================================================================
nav:
  - üè° Sorix: index.md
  # - ‚ú® Features: features.md
  - üìö Learn:
    - Basics:
      - Tensor: learn/basics/01-tensor.ipynb
      - Computational Graph: learn/basics/02-graph.ipynb
      - Autograd: learn/basics/03-autograd.ipynb
    - Layers:
        - Overview: learn/layers/index.md
        - Linear: learn/layers/01-Linear.ipynb
        - BatchNorm1d: learn/layers/02-BatchNorm1d.ipynb
        - ReLU: learn/layers/03-ReLU.ipynb
        - Sigmoid: learn/layers/04-Sigmoid.ipynb
        - Tanh: learn/layers/05-Tanh.ipynb
        - Dropout: learn/layers/06-Dropout.ipynb
        - Module: learn/layers/07-Module.ipynb
    - Loss:
        - Overview: learn/loss/index.md
        - MSELoss: learn/loss/01-MSELoss.ipynb
        - BCEWithLogitsLoss: learn/loss/02-BCEWithLogitsLoss.ipynb
        - CrossEntropyLoss: learn/loss/03-CrossEntropyLoss.ipynb
    - Optimizers:
        - Overview: learn/optimizers/index.md
        - SGD: learn/optimizers/01-SGD.ipynb
        - SGDMomentum: learn/optimizers/02-SGDMomentum.ipynb
        - RMSprop: learn/optimizers/03-RMSprop.ipynb
        - Adam: learn/optimizers/04-Adam.ipynb
        - Comparison: learn/optimizers/05-Comparison.ipynb
        - Optimizer Class: learn/optimizers/06-Optimizer.ipynb
  - Examples:
    - Preprocessing: examples/preprocessing/encoders-scalers-transformers.ipynb
    - Linear Regression: examples/regression/1-linear-regression.ipynb
    - Logistic Regression: examples/regression/2-logistic-regression.ipynb
    - Clustering:
      - K-Means:
        - Iris Dataset: examples/clustering/Iris-dataset.ipynb
        - RandomDatasetGPU: examples/clustering/RandomDataset+GPU.ipynb
    - Neural Network:
      - Regression: examples/nn/1-regression.ipynb
      - Classification:
        - Binary: examples/nn/2.1-classification-binary.ipynb
        - Multiclass: examples/nn/2.2-classification-multiclass.ipynb
        - Iris Dataset: examples/nn/3-Iris_dataset.ipynb
        - MNIST Dataset: examples/nn/4-digit-recognizer.ipynb
  - API Reference: api/


# ====================================================================
# 3. ADVANCED MARKDOWN EXTENSIONS
# ====================================================================
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  
  - pymdownx.blocks.admonition:
      types: 
        - note
        - attention
        - tip
        - warning
        - error
        - info
  - pymdownx.blocks.details
  
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - mdx_include
  - pymdownx.arithmatex:
      generic: true # Use generic syntax ($...$ and $$...$$)


# ====================================================================
# 4. PLUGIN CONFIGURATION
# ====================================================================
plugins:

  - search:
      lang: en
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  # - section-index
  
  - macros:
      module_name: docs/macros
  
  - mkdocstrings:
      handlers:
        python:
          paths: [.] 
          options:
            docstring_style: google
            show_root_heading: true 
            show_source: true
            
            # Advanced Options
            show_if_no_docstring: false
            members_order: source
            separate_signature: true
            signature_crossrefs: true
            merge_init_into_class: true
            docstring_section_style: list
            unwrap_annotated: true
            filters:
              - '!^_'
            
  - mkdocs-jupyter:
      include: ["**/*.ipynb"]
      execute: false
      include_source: true

# ====================================================================
# 5. EXTRAS
# ====================================================================
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Mitchell-Mirano/sorix

extra_javascript:
  # Load formula rendering engine (MathJax)
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js